### ISSUE TITLE
This isn't an issue, more of a personal message.

### ISSUE THREAD

**Issue by Peyton2017** [davidschaeffer2/casper#21]
I assume you have your own Discord server? If you'd like to respond with an invite there that'd be cool. You can also add me on Discord if you're server is private. ZorE#0001. 

I am going to scrap your music module, and merge it with mine currently. To fix queue issues. 
If you have questions, you may add me on Discord. 

PS: Keep up the great work.

**Comment by davidschaeffer2** [comment]
I actually scrapped my music module in the latest commits. I was running into some odd lag issues with it and had more outside requests for the game support instead. While I'm sure I'll get back to it later, it's low priority now. 

Do you mean you have a music module of your own? If you get it merged, I'd love to see what you come up with. I will most likely learn some things. 

I sent you a request on Discord. Keep me posted!
