### ISSUE TITLE
Create a v1.1  milestone for your future work

### ISSUE THREAD

**Issue by Spindel** [davidschaeffer2/casper#3]
Since we're going to have some issues to work on, we need a milestone to sort them into.

Create a v1.1 milestone to work towards!

**Comment by davidschaeffer2** [comment]
Milestone v1.1 - Music cog update is now a milestone I'll be working towards. While there are minor formatting issues to be fixed in other cogs, the Music cog will be the next large update. Issues targeting that milestone can be created and tagged as such.

**Comment by Spindel** [comment]
Excellent work!
