### ISSUE TITLE
And not reddit?

### ISSUE THREAD

**Issue by Spindel** [davidschaeffer2/casper#5]
Code like the one below, which does magical things depending on the filename, should have a comment on _why_ it's behaving like it does.

( I can read it, but there's nothing to explain why it is like this )

https://github.com/davidschaeffer2/casper/blob/eb738e2c4dcb304139bee32ab373abf86b6f29f6/production/casper.py#L22

**Comment by davidschaeffer2** [comment]
This looks like it was an artifact left over from the switch from dev to production. It's been removed and will be reflected in the next push. Thanks for that!

**Comment by davidschaeffer2** [comment]
Removed the 'and not' condition in that line.

**Comment by Spindel** [comment]
Now let's add links between commits and the issues, see the guide [here](https://help.github.com/articles/autolinked-references-and-urls/)
